# Generated by Django 5.2.10 on 2026-02-14 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_stream_options_alter_subject_options_and_more'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xplog',
            name='source',
            field=models.CharField(default='default_source', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectxp',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_records', to='academics.subject'),
        ),
    ]
