# Generated by Django 5.2.10 on 2026-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Game-specific settings in JSON format'),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('quiz', 'Animated Quiz'), ('canvas', 'Canvas Action Game'), ('drag_drop', 'Interactive Sorting'), ('simulation', 'Scientific Simulation')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='max_grade',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='game',
            name='min_grade',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='tmp-slug', help_text='Used for the URL (e.g., equation-archer)', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='game_thumbs/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_imgs/'),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='total_questions',
            field=models.IntegerField(default=1),
        ),
    ]
