# Generated by Django 5.0.1 on 2026-02-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_user_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicclass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.stream'),
        ),
    ]
