# Generated by Django 5.2.10 on 2026-02-14 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guardian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
