# Generated by Django 5.2.10 on 2026-02-14 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_stream_options_alter_subject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('total_games_played', models.PositiveIntegerField(default=0)),
                ('total_minutes_spent', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Snapshot',
                'verbose_name_plural': 'Performance Snapshots',
            },
        ),
        migrations.CreateModel(
            name='StudentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_spent', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_records', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'verbose_name': 'Student Engagement',
                'verbose_name_plural': 'Student Engagement Records',
                'ordering': ['-date'],
            },
        ),
    ]
